# Generated by Django 4.2.1 on 2023-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('book_desc', models.CharField(max_length=100)),
                ('book_cover', models.ImageField(default='', upload_to='covers/')),
                ('pdf_file', models.FileField(default='', upload_to='pdfs/')),
            ],
        ),
    ]
