# Generated by Django 4.2.1 on 2023-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=20),
        ),
    ]
