# Generated by Django 4.2.1 on 2023-06-01 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_bookgenre_name_alter_books_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_genre',
            field=models.ForeignKey(default=1,blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='app1.bookgenre'),
            preserve_default=False,
        ),
    ]
