# Generated by Django 4.2.1 on 2023-06-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_books_book_author_alter_books_book_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.bookgenre'),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.books')),
            ],
        ),
    ]
