# Generated by Django 4.2.1 on 2023-06-02 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_wishlist_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book_cover',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
