# Generated by Django 4.2.1 on 2023-06-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_books_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='app1.bookgenre'),
        ),
    ]
