# Generated by Django 4.2.1 on 2023-06-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_books_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_genre',
        ),
    ]
