# Generated by Django 4.2.1 on 2023-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_wishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='book',
        ),
        migrations.AddField(
            model_name='wishes',
            name='book',
            field=models.ManyToManyField(to='app1.books'),
        ),
    ]
