# Generated by Django 4.2.1 on 2023-06-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_wishes_book_wishes_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='book',
        ),
        migrations.AddField(
            model_name='wishes',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.books'),
        ),
    ]
